import { execExo01 } from "./modules/exo01.js";
import { execExo02 } from "./modules/ex02.js";
import { execExo03 } from "./modules/exo3.js";
import { execExo04 } from "./modules/exo04.js";
import { execExo05 } from "./modules/exo05.js";
import { execExo06 } from "./modules/exo6.js";
import { execExo07 } from "./modules/exo7.js";
import { execExo08 } from "./modules/exo8.js";
import { execExo09 } from "./modules/exo9.js";
import { execExo10 } from "./modules/exo10.js";
execExo01();
execExo02();
execExo03();
execExo04();
execExo05();
execExo06();
execExo07();
execExo08();
execExo09();
execExo10();